### ISSUE TITLE
Worker(NOT Primary) don't init state from genesis block on sidechain

### ISSUE THREAD

**Issue by ziming-zung** [litentry/litentry-parachain#1122]
### Context
related to #999 
There is a problem when launching 2 tee-workers,  worker1(not primary) synchronizes the sidechain block not starting from the genesis block.

Initialize the state,  see at:
https://github.com/litentry/litentry-parachain/blob/3c6a925f48cc6f26fd6c63f7d28be6cb5326f718/tee-worker/enclave-runtime/src/tls_ra/tls_ra_client.rs#L123-L127

So if we want tee-worker to sync sidechain blocks from the genesis block,  we may need to modify this:
https://github.com/litentry/litentry-parachain/blob/3c6a925f48cc6f26fd6c63f7d28be6cb5326f718/tee-worker/enclave-runtime/src/tls_ra/tls_ra_server.rs#L127-L131

I don't find a function to read state at a specified block, like: `query_state_block_at`

**Comment by Kailai-Wang** [comment]
This seems to be the root cause: https://github.com/litentry/litentry-parachain/blob/7aa3dca0e628b4f251e969e0e4c05f1266db7d4e/tee-worker/sidechain/consensus/common/src/block_import.rs#L135

so:
- non-primary worker retrieves the latest state from the primary worker via MU-RA
- when importing sidechain blocks, non-primary worker uses the sidechain block attached in the state as "last known block", despite not having it locally

If we want to sync it from the genesis block, we should use `None` here
I don't know if that's the design or a bug.

**Comment by Kailai-Wang** [comment]
Simply commenting out the state reading in TLS client seems to work, as a result, the `last_imported_block_hash` would be 0x0000 (default) and it will import sidechain blocks from #0.

```rust
--- a/tee-worker/enclave-runtime/src/tls_ra/tls_ra_client.rs
+++ b/tee-worker/enclave-runtime/src/tls_ra/tls_ra_client.rs
@@ -123,7 +123,8 @@ where
                match header.opcode {
                        Opcode::ShieldingKey => self.seal_handler.seal_shielding_key(&bytes)?,
                        Opcode::StateKey => self.seal_handler.seal_state_key(&bytes)?,
-                       Opcode::State => self.seal_handler.seal_state(&bytes, &self.shard)?,
+                       // Opcode::State => self.seal_handler.seal_state(&bytes, &self.shard)?,
+                       _ => (),
                };
                Ok(Some(header.opcode))
        }
```

**Comment by kziemianek** [comment]
There is no need to sync from genesis block after receiving state snapshot from trusted peer. It's by design.
