### ISSUE TITLE
event UnshieldedFunds can't be deposited on Parachain

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1162]
Run the trusted `unshield-funds` call, 

https://github.com/litentry/litentry-parachain/blob/07406acd8e2ead8ca9a1b24948a32b66463a301a/tee-worker/cli/demo_shielding_unshielding.sh#L136

it could transfer funds successfully between `ICGACCOUNTALICE` and `ICGACCOUNTBOB` in tee-worker. 

At the same time a call is sent from tee-work to parachain: https://github.com/litentry/litentry-parachain/blob/07406acd8e2ead8ca9a1b24948a32b66463a301a/tee-worker/app-libs/stf/src/trusted_call.rs#L273-L279

But it seems the event `Event::UnshieldedFunds` on parachain  is missing, which should be deposited by
https://github.com/litentry/litentry-parachain/blob/07406acd8e2ead8ca9a1b24948a32b66463a301a/pallets/teerex/src/lib.rs#L241-L247

**Comment by Kailai-Wang** [comment]
There's no problem in the code logic, the reason why there's no event is the extrinsic fails to execute due to `InsufficientBalance`.

Our ED is 0.1 LIT, but we are trying to shield/unshield 0.05 LIT:
```
AMOUNTSHIELD=50000000000
AMOUNTTRANSFER=25000000000
AMOUNTUNSHIELD=15000000000
```

In this sense the shielding/unshielding should actually check the extrinsic status before making sidechain state changes - but that's a bigger change. For now we can simply make the amount > ED. 

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/7630809/211338574-99fd88b7-67ad-4649-8841-c2cc5b9401b1.png">

**Comment by jingleizhang** [comment]
The new script works fine. Thanks all!

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/7367842/211450473-b9213c94-d6a0-48a2-8702-1f593170a934.png">
