### ISSUE TITLE
Resume-worker test times out

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1346]
### Context
It happened a few times already, see e.g. https://github.com/litentry/litentry-parachain/actions/runs/4202077590

The logs are a bit spammy so it's hard to find the really useful logs

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
Keep notice on #1124

**Comment by Kailai-Wang** [comment]
https://github.com/litentry/litentry-parachain/actions/runs/4651018408

[logs-lit-resume-worker.zip](https://github.com/litentry/litentry-parachain/files/11186114/logs-lit-resume-worker.zip)

**Comment by arieljbirnbaum** [comment]
After #1846, the failing scenarios here seem to always be the two-worker ones; mostly the "kill both workers and restart both" one. Since multiworker mode isn't reliably working at the moment, it's unlikely that we can stabilize the test script.

For now, we should drop the multiworker scenarios. PR #2041 .

Do we have an issue (or a list thereof) to track the work needed for enabling multiworker mode? We should add a note there to reimplement these tests at that moment; I also want to leave a link to that issue from the test script to track the debt.
