### ISSUE TITLE
VC: credentialSubject.id is missing address prefix

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1388]
One example VC:
> {
	"id": "0x9fbb82de6a46d75e1af28e86d1b83d0d40a3473754ed185ee9cb55b9a5967660",
	"credentialSubject": {
		"id": "d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
	}
}

its credentialSubject.id is `d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d` that means the owner account of this credential. 

But in the VCRegistry,  key is: 
> 0x9fbb82de6a46d75e1af28e86d1b83d0d40a3473754ed185ee9cb55b9a5967660

value is:
> {
  subject: jcS2wD5jDwouCqVABGCZhVjKQQm3ZHxMYTabySfT3Pygzck9W
  hash_: 0x2dbfb76de62cdd339ed6b43824c77fcf042da8ae677548bc2e5bc199c6b1324a
  status: Active
}

The subject `jcS2wD5jDwouCqVABGCZhVjKQQm3ZHxMYTabySfT3Pygzck9W` also means the owner account. It doesn't equal credentialSubject.id.

bug: 
`credentialSubject.id` is missing the address prefix.

**Comment by Kailai-Wang** [comment]
In fact, I think it's better to keep `credentialSubject.id` as the public key address format => the VC is arrogant to network: when TEE issues a VC, it doesn't need to know who will get the VC (if it's someone on litentry parachain or litmus parachain, or even some ETH user in the future). With the hash, vc-id, owner you can always uniquely verify a VC from the registry.

The `subject` in `VCRegistry` can also be either of them, ss58 address or pubkey. If you believe pubkey is better (so that it's aligned with the `credentialSubject.id`, we can change that, otherwise we can leave it as it is (VC verifiers can do the conversion and compare - it's just one line of code).

What do you think? @jingleizhang

**Comment by jingleizhang** [comment]
Let's leave them as they are right now. Close this issue.
