### ISSUE TITLE
too many requests at the same time to Parachain&TEE

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1520]

**Comment by jingleizhang** [comment]
add @zhouhuitian

**Comment by outofxxx** [comment]
@Verin1005 
Is this question a duplicate of this pr https://github.com/litentry/litentry-parachain/pull/1529?

**Comment by outofxxx** [comment]
got `verifyIdentityFailed` after a successful IdentityVerified

 set the descriptedLitentry number to 10, then run bulk_identity.test.ts, the issue will appear

discussed in [channel](https://litentry.slack.com/archives/C03KR96989G/p1681747270391789)

**Comment by Kailai-Wang** [comment]
What is the context for the issue?

Neither @zhouhuitian nor I have the knowledge - we always need a short summary/background introduction in the issue description.

**Comment by outofxxx** [comment]
The purpose of this issue record is to test the request scripts related to multiple accounts in the staging/prod2 environment, mainly the bulk_identity and bulk_vc scripts in ts-test.
The issues currently found are the same as those discussed in the channel above, where after verifyIdentity succeeded, a failed event appeared again.

**Comment by 0xverin** [comment]
Since the `utility` and `bulk` tests are already covered in ts-tests, [this issue](https://github.com/litentry/litentry-parachain/issues/1562)(encountered during stress testing) needs further investigation. For now, let's lower the priority to low. If there is a need for stress testing in the future, we can raise the priority back to high. cc @zhouhuitian

**Comment by outofxxx** [comment]
The stress testing covered this case already, so let's close it.
