### ISSUE TITLE
multiple accounts createIdentity bug

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#1561]
local env:node+tee
local startup command:
`./target/release/integritee-node --rpc-cors=all --ws-external --tmp --dev`
`./local-setup/launch.py local-setup/github-action-config.json`

Reproduce this bug:
-   dev branch `bulk_identity.test.ts`
- describeLitentry number set to 10
- `yarn run test-bulk-identity:local`

Bug description:
create 10 identities ,get 10 `CreateIdenityRequestd` event,but only one `IdentityCreated` event

See the screenshot below：
![image](https://user-images.githubusercontent.com/104152026/229558371-046810cc-4f1c-4a54-bac1-91ec6801fbf6.png)
![image](https://user-images.githubusercontent.com/104152026/229558389-ad436d49-83df-4a2a-90a2-4998933a347e.png)
![image](https://user-images.githubusercontent.com/104152026/229558438-5996d206-4678-4a1a-984d-830601e451f1.png)
<img width="1931" alt="image" src="https://user-images.githubusercontent.com/104152026/229558460-74e3dc8c-144f-466d-991c-3100f757525b.png">

Note that although `createIdentityRequested` is shown as one, there are actually 10 inside. `IdentityCreated` only has one inside.
 
@zhouhuitian also encountered a similar problem in Rust test and can supplement it here.

**Comment by Kailai-Wang** [comment]
I can _somewhat_ reproduce it.

Got `balance too low` error when I ran it.

I had to change the fund to 2 LIT instead of 0.1 LIT.

Then I got 9 extrinsic failures:
```
system.ExtrinsicFailed [{"module":{"index":64,"error":"0x01000000"}},{"weight":{"refTime":115974000,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
```

This error points to `UnauthorisedUser`:
https://github.com/litentry/litentry-parachain/blob/67d488c7454f17410fe82031b0201d1b11e5a9cb/pallets/identity-management/src/lib.rs#L165

It means you used the wrong parameter when calling `create_identity`, the `user` has to be either the sender himself, or in the delegatee list.

**Comment by 0xverin** [comment]
[this](https://github.com/litentry/litentry-parachain/blob/dev/tee-worker/ts-tests/common/utils.ts#L687) bug causes issue described error.It has been fixed.This issue can be saved for later questions.

**Comment by Kailai-Wang** [comment]
Can this ticket be closed?

**Comment by 0xverin** [comment]
> 
This can be closed
