### ISSUE TITLE
Reivew VC fields

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1861]
### Context

VC undergoes variant transmission channels: top pool buffer, internal mpsc, ocall, extrinsic.

Reducing the VC size would help improve the performance/latency.

However, before doing that, we need to review the structure to see if we have proper fields at all.

### Tasks:
- compare the current VC structure with w3c standards or even VCs generated from other projects:
   - are we missing any fields?
   - do we wrongly populate any fields?
   - are all additional fields necessary?
 - based on that, check if we can shorten the VC size by e.g. removing redundant fields, or populating it with a shorter representation.
 - (optional) using any "standard" VC parser tool to parse our VC, does it work?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
* **@context**
  * ```["https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/ed25519-2020/v1"]```
  * let's keep it as it is
* **id**
  * generated randomly, example: `0x90d9a1227dfd524693f927db7fc8aa6b39231d1ca7efd96c7f53b70604536190`
  * It should meet following requirements:  </br> The id property MUST express an identifier that others are expected to use when expressing statements about a specific thing identified by that identifier. </br> The id property MUST NOT have more than one value. </br> The value of the id property MUST be a URI.
* **type**
  * `["VerifiableCredential"]`
  * We can use more specific types but that would increase size of generated VCs, example: `["VerifiableCredential", "UniversityDegreeCredential"]`
* **credentialSubject**
  * ```{"id":"5c5d33eb2187f2a769e0fdf34a1c4c3a24b83223f6e46e9aad89a9f39b2baf10","description":"The user has obtained an ID-Hubber role in a Litentry Discord channel","type":"Discord ID-Hubber Role Verification","tag":["Discord"],"assertions":[{"and":[{"src":"$verified_discord_account","op":">","dst":"0"},{"src":"$has_joined","op":"==","dst":"true"},{"src":"$discord_guild_id","op":"==","dst":"807161594245152800"}]}],"values":[false],"endpoint":"wss://tee-staging.litentry.io"}```
  * We can get rid of enpoint because there is issuer field. If we know who issues VC, then we should be able to find actual endpoint. In our Rust model we also have data_source but it's not used so it's not present in generated VCs
  * We can make descriptions less verbose.
  * We can get rid of `tag` field. Doesn't serve any purpose.
* **issuer**
  * ```{"id":"13d25960c4bcd91a691ddf9609d741ffe1653aab7146890af56e61bf4518c4b7","name":"Litentry TEE Worker","mrenclave":"5EkB2WLx7YtCGbnQZYkA9efwjU6ns67jpfuicAaqexFa"}```
  * We can store only id of the issuer, clients can get rest of fields from parachain teerex pallet
* **issuanceTimestamp**
  * `1689839352573`
  * We should switch to another format 2010-01-01T19:23:24Z, see https://www.w3.org/TR/xmlschema11-2/#dateTime
* **proof**
  * We should rename `created_timestamp` to `created`

**Comment by Kailai-Wang** [comment]
Thanks @kziemianek 

- id
   shall we change it to URI-like value? _The value of the id property MUST be a URI._
- type
   should it be a dynamic field then? (which e.g. comes from the registered jsonschema)
- credentialSubject.id
   do we need a `did:litentry:...` format for it? To be more standard compliant
- issuer
   what's actually the id here? How is it calculated?
- proof
   maybe need a follow-up discussion: what should the proof message be here

**Comment by kziemianek** [comment]
@Kailai-Wang:
*  yes all ids should be a URI.
* type - depends if we want more specific types - not sure about that. Better be conservative - as long as there is no strong reason to introduce anything, let's keep it as it it.
* issuer - id is a hex representation of scale encoded `AccountId` - 
* proof - yes, let's have a follow-up discussion

**Comment by kziemianek** [comment]
At this moment we only know that issuer's addresses comes from `litmus` / `litentry` network.
Subject's addresses are network agnostic thus we cannot determine it. We simply cannot use `did:litentry:...` or `did:ethereum:...`. We can use `did:substrate:..`  / `did:evm:..` instead and I think we should do the same in case of `issuer's id.

**Comment by Kailai-Wang** [comment]
@kziemianek shall we do the adjustments according to the [notion doc](https://www.notion.so/web3builders/Review-VC-fields-d7132757fcdc4554b53b1f4ab93ab507)?

**Comment by kziemianek** [comment]
@Kailai-Wang, yes. There are two things to do left: ids (credentialSubject and issuer) and proof.

Ids will have have DID format according to the table below:
| identity type | format |
|--------- | ---------|
| substrate | did:litentry:substrate:0x12345... |
| evm | did:litentry:evm:0x123456... |
| twitter | did:litentry:twitter:my_twitter_handle |

In case of proof we will change a message to sign from VC's json to mrenclave value.

**Comment by Kailai-Wang** [comment]
This is done - and you'll see the changes if you spin up the network from the `dev` branch @jonalvarezz
