### ISSUE TITLE
Error message: [MU-RA-Server] ECALL Enclave Failed Sgx(SGX_ERROR_UNEXPECTED)!

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1931]
### Context
Recently there are quite many error message coming out from Staging env on `alert` channel:
```
[2023-07-23T02:59:56Z ERROR integritee_service::enclave::tls_ra] [MU-RA-Server] ECALL Enclave Failed Sgx(SGX_ERROR_UNEXPECTED)!
```

### Task
Please investigate it and bring up a solution.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
When the key provisioning server receives a connection, it will read the shard information sent by the client, as shown in code: 

https://github.com/litentry/litentry-parachain/blob/055b19d358089b0ed2f9571a23badbd82c638f6d/tee-worker/enclave-runtime/src/tls_ra/tls_ra_server.rs#L90-L94

If the read fails, it will return, `read_ exact` method can be found in https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/io/trait.Read.html#method.read_exact.

Therefore, when this error is returned from enclave, a message will be thrown `ECALL Enclave Failed Sgx(SGX_ERROR_UNEXPECTED)`. 

Also, because the key server is based on TLS, receiving information or incorrect data from an unsafe client can trigger this error.

I can trigger this warning by using the following simple client for local testing.
```python
import socket
import random

host = "0.0.0.0" 
port = 3443
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((host, port))

no_of_bytes = 32
rand_bytes = random.randbytes(no_of_bytes)
s.send(rand_bytes)

data = s.recv(1024)
s.close()
print('Received', repr(data))

```

So, this is just a warning thrown by enclave that the read client shard failed, and I think it should be ignored.

**Comment by Kailai-Wang** [comment]
Thank you!
Do you have an idea why it didn't happen before?  Is it related to how IDH connects to the sidechain? 

cc @jonalvarezz

**Comment by jonalvarezz** [comment]
It sounds related to the mismatched mrenclave values after restarts  -> IDHub sends "wrong" shard. 

Could it be caused while working on integrating new types? Getting it right is a fail-and-retry task for us.

> Is it related to how IDH connects to the sidechain?

to confirm: this hasn't change since we onboarded DI. IDHub connects with TLS checks disabled from a proxy server.

**Comment by outofxxx** [comment]
@niteshb3495 Can you remove this alert from the script.

**Comment by outofxxx** [comment]
Nitesh has disabled this alert, so it can be closed now.
