### ISSUE TITLE
ClassOfYear VC returns false for linked EVM addresses

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2044]
### Context

It was initially reported by the community, and it occurred in my tests too.

Steps to reproduce:
- login with EVM address, set shielding key
- request this VC -> Ok
- link a bunch of EVM addresses
- request this VC -> issued by `value == false`

This must be wrong - it can't be worse than the first attempt

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
This bug is caused by premature exit when parsing to an invalid `metadata` field, such as addresses A(2021)/B(invalid)/C(2019), requesting the B address causing the parsing of 'metadata' to fail, directly returning false, resulting in the generation of a false VC. Now modify to request all addresses and return with the most suitable year.
