### ISSUE TITLE
Unexpected end of JSON input issue in CI

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#2081]
### Context
See 
https://github.com/litentry/litentry-parachain/actions/runs/5988781615/job/16250635843?pr=2016 https://github.com/litentry/litentry-parachain/actions/runs/6010733191/job/16308503413?pr=2035
https://github.com/litentry/litentry-parachain/actions/runs/6012187847/job/16307451317?pr=2066

Rerunning the workflow resolves this issue. We need to investigate it. :(

Since it affects the CI process for all PRs, I've temporarily marked it as a high-priority issue. Please feel free to adjust if it's not appropriate.

**Comment by Kailai-Wang** [comment]
I wrote a minimal reproducible example:

```
// @ts-ignore
import * as shell from 'shelljs';

const getChainspec = (image: string, chain: string) => {
    let res;
    if (chain.endsWith('.json')) {
      res = exec(
        `docker run -v $(pwd)/${chain}:/${chain} --rm ${image} build-spec --chain=/${chain} --disable-default-bootnode`
      );
    } else {
      res = exec(`docker run --rm ${image} build-spec --chain=${chain} --disable-default-bootnode`);
    }
  
    let spec;
  
    try {
      spec = JSON.parse(res.stdout);
    } catch (e) {
      return fatal('build spec failed', e);
    }
  
    return spec;
};

const exec = (cmd: string, fatal = true) => {
    console.log(`$ ${cmd}`);
    const res = shell.exec(cmd, { silent: true });
    if (res.code !== 0) {
      console.error('Error: Command failed with code', res.code);
      console.log(res);
      if (fatal) {
        process.exit(1);
      }
    }
    return res;
  };

const fatal = (...args: any[]) => {
    console.trace('Error:', ...args);
    process.exit(1);
  };

function delay(ms: number) {
    return new Promise( resolve => setTimeout(resolve, ms) );
}

for (let i = 0; i < 10; i++) {
    getChainspec("litentry/litentry-parachain:latest", "rococo-dev");
}
```

**Comment by Kailai-Wang** [comment]
I submitted an upstream PR for it

**Comment by 0xverin** [comment]
> I submitted an upstream PR for it

Thanks!

**Comment by Kailai-Wang** [comment]
It turns out that relaychain chain spec can be broken too: https://github.com/litentry/litentry-parachain/actions/runs/6024693713/job/16348364062

I believe the root cause is it exports the genesis wasm and inject it into the relaychain chain spec. I managed to reproduce it locally by running it multiple times:

Note the size of `/tmp/rococo-local-8.json`

<img width="694" alt="image" src="https://github.com/litentry/litentry-parachain/assets/7630809/79324b8c-da2b-49d7-aace-f6b2ebff8721">

After changing it to reading from file it looks good:

<img width="618" alt="image" src="https://github.com/litentry/litentry-parachain/assets/7630809/92116475-1f38-40cc-b919-7e83bf0f8b9f">
