### ISSUE TITLE
Fix CI does not detect spec_name mismatch

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#214]
As mentioned in https://github.com/litentry/litentry-parachain/commit/352a6f9ca320c34007380891171d8f746c349e30
Our CI passes but since we did not match `spec_name` and `impl_name` with `litentry-parachain-runtime`, extrinsic failed to submit, the log shows
```
Failed to submit extrinsic: Extrinsic verification error: Runtime error: Execution failed:
Other("Wasm execution trapped: wasm trap: unreachable ...
```

**Comment by geastwood** [comment]
The error message is not helpful at all. How people can deduct the fact the name mismatch is the reason for the error?
Or am I missing anything?

**Comment by Satoshi-Kusumoto** [comment]
> The error message is not helpful at all. How people can deduct the fact the name mismatch is the reason for the error? Or am I missing anything?

You can check the commit link and it is the bug fix
No PR just because it was an urgent quick fix

**Comment by Kailai-Wang** [comment]
In rurst-logs the panic comes from `impl_runtime_apis!` macro in `runtime/src/lib.rs`.
On polkadot-JS everytime when submitting transaction without the fix, this error was shown:

![image](https://user-images.githubusercontent.com/7630809/140552827-608c06a3-64de-45ae-9d16-1bfb4d4a4f13.png)

**Comment by Kailai-Wang** [comment]
It might take some time to figure out the root cause, because even with the unmatched versions, `@polkadot/api` couldn't detect it (or it doesn't care).

Since these names are now unlikely to change, I'd suggest simply adding a CI-check to guard the potential inconsistency. Ideally a JS test which could simulate the polkadot-js UI, or if we want to simplify it, just a sanity check of `spec_name` and `impl_name` with runtime package name check.

**Comment by Kailai-Wang** [comment]
This could be closed now as we are not going to change the runtime package name whatsoever
