### ISSUE TITLE
Setup parachain DB backup

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#217]
- [x] Able to do snapshot periodically
- [x] Optionally have a dedicated archive node

**Comment by Kailai-Wang** [comment]
We could keep an eye on this:
https://stackoverflow.com/questions/69987809/what-is-the-right-way-to-back-up-a-substrate-basepath

**Comment by Kailai-Wang** [comment]
I think we need both:
- run our own archive node: it only needs to sync (parachain) DB, the hardware doesn't have to be very good.
- make DB snapshot from the archive node (everyday or every few days)

**Comment by niteshb3495** [comment]
The db backup scripts are setup on staging and production. if, because of some reason, db backup fails, we will get a slack notification in [#alert](https://litentry.slack.com/archives/C01NT5M9HGR) channel from respective env (staging or prod). (The sample alert is already generated in the channel.)

The script will run at 23.55 everyday UTC and it will store the backup on S3 bucket ([litentry-db-backup](s3://litentry-db-backup)) directly.

The bucket has two folders in it, staging and production, storing respective db backups.
staging backup is from: **parachain-sg-staging-0**
production backup is from: **litmus-parachain-sg-rpc-0-prod**

Please let me know if any change is required.

**Comment by Kailai-Wang** [comment]
Hi @niteshb3495 , how is this one going?
Have you addressed this issue?
> I mean your [else branch](https://github.com/Litentry-Dark/devops-scripts/blob/2c698a9abb80d9eb6724528e62dd5ca94687e6e4/parachain-db-backup.sh#L48) will never be triggered, because the file will always be created, no matter if full exists or not

**Comment by niteshb3495** [comment]
Hi @Kailai-Wang 
I have updated the script to check the tar file status after creation. Also check the #alert channel on slack for sample notification from staging.

**Comment by Kailai-Wang** [comment]
Thanks.

A few small things:
- can we increase the waiting time between `stop_service` and `db_backup`? I'm not sure if the service is stopped synchronously (depends on how the binary handles the signal). 5 sec might be too short. Can we make it like 15 s or so? Or use a while loop
- the `exit 0` in the tar file status check might be confusing. IMHO it's better to have another exit code than default as it indicates an error.
- about the path or the name of DB: I'd expect to have something like `litmus-parachain` or `litentry-parachain` (later for polkadot) in its name, otherwise it's hard to figure out which DB backup it is: `20220301.tar.gz`

**Comment by niteshb3495** [comment]
Thanks.

1. Usually, 5 seconds are more than enough to stop the service unless there are a lot of busy child process. But yes, I can increase the time. 
2. Let's discuss this in slack. 
3. Noted. I will change the name of the database dump to add service (variable) in it.

**Comment by Kailai-Wang** [comment]
This is done, now parachain DB snapshot will be uploaded to [AWS S3](https://s3.console.aws.amazon.com/s3/buckets/litentry-db-backup?prefix=production%2F&region=ap-southeast-1&showversions=false#) on a daily basis.

Close it now
