### ISSUE TITLE
Bug: failed to generate OneBlock+ credential

### ISSUE THREAD

**Issue by kaylawangnow** [litentry/litentry-parachain#2179]
### Case 1 Reproduce steps
https://idhub.litentry.io/
1. Add my testing address to source form [学员信息表](https://www.notion.so/9ebb55be96a64511b32cd0d5e6457f1b?pvs=4) 
2. Sign in IDHub with my EVM account as primary account
3. Link my testing address to my ID Graph (Polkadot network selected)
4. Request credential: failed to establish

### Case 2 Reproduce steps
https://identity-hub-git-v04-litentry.vercel.app/
1. Add my testing address to source form [学员信息表](https://www.notion.so/9ebb55be96a64511b32cd0d5e6457f1b?pvs=4) 
2. Sign in IDHub with my testing address as primary account
4. Request credential: failed to establish

My testing address: 
16ALMzbcymnBV4BEq32yi9oeE1ATuLGpGBy5DoXUjMTW4K9B (polkadot) (this is what I added in the form)
5HE3DfLZ7zWi3XAisPyyZzyVNPApD2igBhEb4WY8BGRysqbK (substrate) (this is how it appears in idhub)

**Comment by outofxxx** [comment]
I have looked at the data in the[ student table ](https://www.notion.so/9ebb55be96a64511b32cd0d5e6457f1b?pvs=4) and if there is a need to add new test data, the **student number** should be consistent with the previous one, using **numerical** numbers instead of letters. This is my test result.

![image](https://github.com/litentry/litentry-parachain/assets/125243011/9b119b53-cbdf-4ed8-a715-7759816b8f99)



So, you can modify the number and test it again.

**Comment by outofxxx** [comment]
False alert.  
New added item's student number should keep using numerical number. 
so, Close it.
