### ISSUE TITLE
Replace the Integritee node with our parachain

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#531]
- Replace the Integritee node with our parachain
- Apply config changes
- Check our parachain is up-to-date

**Comment by Kailai-Wang** [comment]
> Check our parachain is up-to-date

This is related to #488 , especially when upstream sgx-runtime and worker were updated to `polkadot-v0.9.19` branch already.

**Comment by Kailai-Wang** [comment]
Maybe this issue could be merged with https://github.com/litentry/litentry-parachain/issues/481, at least not blocking.

To replace intergritee-node with our parachain, we need to add teerex pallet in our parachain. It can't be replaced without integration of teerex pallet. It's not strictly blocked by #481 either, because to verify if teerex pallet works, we need to use our parachain throughout the CI.

What do you think @StamfordDigital?

Alternatively, we could still keep them separated, but for #481 we are only supposed to (literally) add the pallet and make sure it doesn't break the parachain's CI/CD. In that case, the estimation for #481 can be reduced to 2 days. => I'll prefer this.

**Comment by StamfordDigital** [comment]
@Kailai-Wang as mentioned on Slack. I've reduced the estimation for #481 to **2 days**.

**Comment by Kailai-Wang** [comment]
It's not strictly blocked, but ideally we would start this after the upstream version switch is done: https://github.com/integritee-network/worker/issues/694
