### ISSUE TITLE
Benchmark update

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#794]
### Context
For the following pallets:

- [x] bridge
- [x] bridgeTransfer
- [x] parachainStaking

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
I assign this ticket to you both @wangminqi and @Jinsipang. It's not super urgent but we need to have this done before token bridge is onboarded on Litentry.

**Comment by Marky-Shi** [comment]
After adding the benchmark code to the bridge-transfer pallet, running the transfer_native and transfer methods, the test results have been failures, starting with `Bad Origin` because where these two methods are implemented, the origin needs to be verified. After that I tried to add the account constructed in benchmark to the list of allowed to call these two methods, but it is still not feasible, perhaps it is a problem with my coding, I hope you can give some advice, the branch name [issue_794](https://github.com/litentry/litentry-parachain/tree/issue_794) @Kailai-Wang
